### ISSUE TITLE
docker build fails with "No module named 'nbserverproxy'" for v0.8.0

### ISSUE THREAD

**Issue by stropa** [jupyterhub/jupyter-rsession-proxy#63]
building image from v0.8.0 tag fails

```
docker build -t jupyterhub/jupyter-rsession-proxy:0.8.0 .
```

```Step 11/17 : RUN jupyter serverextension enable --sys-prefix --py nbserverproxy
 ---> Running in d0dbaa0883c8
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-serverextension", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.7/site-packages/notebook/serverextensions.py", line 294, in start
    super(ServerExtensionApp, self).start()
  File "/opt/conda/lib/python3.7/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/opt/conda/lib/python3.7/site-packages/notebook/serverextensions.py", line 211, in start
    self.toggle_server_extension_python(arg)
  File "/opt/conda/lib/python3.7/site-packages/notebook/serverextensions.py", line 200, in toggle_server_extension_python
    m, server_exts = _get_server_extension_metadata(package)
  File "/opt/conda/lib/python3.7/site-packages/notebook/serverextensions.py", line 328, in _get_server_extension_metadata
    m = import_item(module)
  File "/opt/conda/lib/python3.7/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
ModuleNotFoundError: No module named 'nbserverproxy'
```

**Comment by ryanlovett** [comment]
Thanks for the report. We recommend you install version jupyter-rsession-proxy version 1.0b6 (not tagged) to use with jupyter-server-proxy.
