### ISSUE TITLE
Terminal not working in RStudio

### ISSUE THREAD

**Issue by anton-khodak** [jupyterhub/jupyter-rsession-proxy#71]
Hello! When I run `jupyter-rsession-proxy` with this [Dockerfile](https://github.com/jupyterhub/jupyter-rsession-proxy/issues/65#issuecomment-494604759) and try opening a terminal in RStudio, I get the following error in console:
```
[I 09:15:51.316 NotebookApp] Trying to establish websocket connection to ws://localhost:46203/p/a345fca3/terminal/C3090FD3/
[E 09:15:51.471 NotebookApp] Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f35952d9b38>>, <Task finished coro=<ProxyHandler.proxy_open.<locals>.start_websocket_connection() done, defined at /opt/conda/lib/python3.7/site-packages/jupyter_server_proxy/handlers.py:258> exception=HTTP 404: Not Found>)
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
        ret = callback()
      File "/opt/conda/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
        future.result()
      File "/opt/conda/lib/python3.7/site-packages/jupyter_server_proxy/handlers.py", line 263, in start_websocket_connection
        on_message_callback=message_cb, on_ping_callback=ping_cb)
    tornado.httpclient.HTTPClientError: HTTP 404: Not Found
```
and the terminal displays nothing
![image](https://user-images.githubusercontent.com/10351924/60332219-41cefa00-998e-11e9-912b-df3acb36832b.png)

**Comment by riazarbi** [comment]
Me too - 

```
[I 20:02:26.977 NotebookApp] Trying to establish websocket connection to ws://localhost:54789/p/af1d970b/terminal/418A9C1A/
[E 20:02:26.980 NotebookApp] Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7fd7ceb825c0>>, <Task finished coro=<ProxyHandler.proxy_open.<locals>.start_websocket_connection() done, defined at /usr/local/lib/python3.6/dist-packages/jupyter_server_proxy/handlers.py:258> exception=HTTP 404: Not Found>)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 743, in _run_callback
        ret = callback()
      File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 767, in _discard_future_result
        future.result()
      File "/usr/local/lib/python3.6/dist-packages/jupyter_server_proxy/handlers.py", line 263, in start_websocket_connection
        on_message_callback=message_cb, on_ping_callback=ping_cb)
    tornado.httpclient.HTTPClientError: HTTP 404: Not Found
[E 20:02:49.098 NotebookApp] Uncaught exception POST /rstudio/events/get_events (192.168.2.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='POST', uri='/rstudio/events/get_events', version='HTTP/1.1', remote_ip='192.168.2.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/usr/local/lib/python3.6/dist-packages/jupyter_server_proxy/handlers.py", line 434, in proxy
        return await super().proxy(self.port, path)
      File "/usr/local/lib/python3.6/dist-packages/jupyter_server_proxy/handlers.py", line 199, in proxy
        response = await client.fetch(req, raise_error=False)
    tornado.simple_httpclient.HTTPTimeoutError: Timeout during request
```
Salient parts of [my Dockerfile](https://github.com/riazarbi/jupyter-rstudio-proxy/blob/master/r-base/Dockerfile) - 

```
RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install jupyter jupyterhub jupyterlab
...
...

 && python3 -m pip install git+https://github.com/jupyterhub/jupyter-server-proxy \
 && python3 -m pip install git+https://github.com/jupyterhub/jupyter-rsession-proxy

**Comment by riazarbi** [comment]
A workaround I have found is to turn off websockets under Tools ->  Global Options -> Terminal. This fixes it. Not sure how to set this programmatically so I can bake it into an image...

**Comment by riazarbi** [comment]
Another workaround is to use the pypi version of `jupyter-rsession-proxy` rather than the github version. This is version `1.0.b6` and terminal works with websockets.

**Comment by zjiaksmc** [comment]
I figure out another workaround. I manually change the global options in my session, export the user-settings file from /home/jovyan/.rstudio/monitored/user-settings/, then use kuberspawner lifecycle_hooks to copy this user-settings to the home directory of every user who try to spawn a rstudio container.
`lifecycle_hooks = {"postStart": {
                                              "exec": {
                                                  "command": ["/bin/sh", "/etc/rstudio/config-rstudio.sh"]
                                              }
                                }}`
config-rstudio.sh can be like 
`mkdir /home/jovyan/.rstudio/monitored/user-settings -p && 
cp /etc/rstudio/user-settings/user-settings /home/jovyan/.rstudio/monitored/user-settings/
`

**Comment by FernandezMathieu** [comment]
@anton-khodak Hi, did you found a solution for this ? I am facing the same problem.

**Comment by prete** [comment]
@FernandezMathieu 
With @anton-khodak we got it working using `rstudio-server-1.2.5019-amd64.deb` with the latest `jupyter-server-proxy` and [juvipanda's jupyter-rsession-proxy](https://github.com/yuvipanda/nbrsessionproxy/archive/rserver-again.zip).

Relevant parts of our Dockerfile
```Dockerfile
# jupyter-server-proxy extension
RUN pip install jupyter-server-proxy
# use yuvipanda version of jupyter-rsession-proxy (nbrsessionproxy)
RUN pip install https://github.com/yuvipanda/nbrsessionproxy/archive/rserver-again.zip
RUN jupyter serverextension enable --sys-prefix jupyter_server_proxy
```

**Comment by BigDataRsk** [comment]
> @FernandezMathieu
> With @anton-khodak we got it working using `rstudio-server-1.2.5019-amd64.deb` with the latest `jupyter-server-proxy` and [juvipanda's jupyter-rsession-proxy](https://github.com/yuvipanda/nbrsessionproxy/archive/rserver-again.zip).
> 
> Relevant parts of our Dockerfile
> 
> ```dockerfile
> # jupyter-server-proxy extension
> RUN pip install jupyter-server-proxy
> # use yuvipanda version of jupyter-rsession-proxy (nbrsessionproxy)
> RUN pip install https://github.com/yuvipanda/nbrsessionproxy/archive/rserver-again.zip
> RUN jupyter serverextension enable --sys-prefix jupyter_server_proxy
> ```

Well, i try with your configuration but it still don't work. 
Anyway i think the problem come from my distribution (centOS).
Thanks for the reply !

**Comment by prete** [comment]
If you share your Dockerfile perhaps we can find the main differences and go from there. You can find our whole [Dockerfile here](https://github.com/cellgeni/notebooks/blob/master/Dockerfile) _(there be dragons in there)_.

**Comment by hongkunyoo** [comment]
> Well, i try with your configuration but it still don't work.
> Anyway i think the problem come from my distribution (centOS).
> Thanks for the reply !

I'm facing same experience. Works fine on ubuntu host server, while having `tornado.simple_httpclient.HTTPTimeoutError: Timeout during request` on cetnos host sver

**Comment by atopion** [comment]
Hi,
I'm just commenting in case anyone else gets stuck on this page for days like I did. I was getting a similar error: '400 Bad Request' instead of '404 Not Found', but the result was the same: the websockets of the Terminal and RShiny apps didn't work.
Check your proxy settings: In my case, I had an HTTP proxy set up, but I forgot to add `localhost` to the `NO_PROXY` variable. This caused RStudio to try to send WebSocket responses via the proxy.
